### ISSUE TITLE
How do you dump the gameassembly?

### ISSUE THREAD

**Issue by totorowldox** [chrysls/scp-internal-il2cpp#10]
I know im very stupid,but I still have to ask.
How do you dump the gameassembly?

**Comment by JosiahBeaulieu** [comment]
Use il2cpp dumper: https://github.com/Perfare/Il2CppDumper
Instead of the game binary, use the gameassembly.dll file and the metadata file is in the SCPSL_Data>il2cpp_data>Metadata folder.

Then use ilspy to look around in the dumpted files.

**Comment by JosiahBeaulieu** [comment]
And you're not stupid, just new. Watch some videos on youtube about ilspy and unity3d hacking, and learn to find offsets using Cheat Engine, I don't know how to find offsets as I'm trying to learn as well, but I'm getting there and you'll get there too.

**Comment by totorowldox** [comment]
I use il2cppdumper before.
but the file seem to be packed.

**Comment by JosiahBeaulieu** [comment]
Packed? What do you mean?

**Comment by totorowldox** [comment]
> Packed? What do you mean?

encryption

**Comment by t1f7** [comment]
> Use il2cpp dumper: https://github.com/Perfare/Il2CppDumper
> Instead of the game binary, use the gameassembly.dll file and the metadata file is in the SCPSL_Data>il2cpp_data>Metadata folder.
> 
> Then use ilspy to look around in the dumpted files.

This doesn't work in scopophobia, because they broke file into segments and load them in memory. One way is to manually dump segments and combine them, you will get most strings and functions back, through I don't know the correct order, it seems file reversred (magic bytes are at the last section)

**Comment by JosiahBeaulieu** [comment]
Oh damn, now that's too advanced for me.
But, could it be possible to dump the code from memory? If so, would it dump in assembly or something else?
I know it's possible to dump asset files from the GPU though.

**Comment by t1f7** [comment]
> Oh damn, now that's too advanced for me.
> But, could it be possible to dump the code from memory? If so, would it dump in assembly or something else?
> I know it's possible to dump asset files from the GPU though.

yeah, it will work.
anyway, what offsets do you want to find?

**Comment by JosiahBeaulieu** [comment]
Well, since the beta release the current offsets are no longer valid, or, I think they aren't as the hack no longer works but does not crash when loading in game.
So I've been trying to understand how offsets work and how to find those offsets, but haven't had much progress using CE.

**Comment by t1f7** [comment]
> Well, since the beta release the current offsets are no longer valid, or, I think they aren't as the hack no longer works but does not crash when loading in game.
> So I've been trying to understand how offsets work and how to find those offsets, but haven't had much progress using CE.

Most functions will never change due to engine. Sig them and scan after update.
`il2cpp_string_new` and `il2cpp_resolve_icall` are exports and you don't really need offset for them

**Comment by JosiahBeaulieu** [comment]
Thanks for updating!

But I do not know what you mean by signing them.
And I mistakenly said before that I'm "trying to understand offsets", what I mean to say was "trying to understand addresses".

**Comment by totorowldox** [comment]
Is there any like DisableHook's method?
or
Tell me how to noclip and bypass the anticheat.

**Comment by JosiahBeaulieu** [comment]
Did they update the anticheat?
Chrysls has put in a workaround for it already a while ago. Probably the addresses need to be updated for it.
And noclip might not be really feasable in a server as once the player is outside the bounds of the map they are automatically killed, and that's serverside. I think you could spoof your camera coordinates to get a freecam.

**Comment by totorowldox** [comment]
> Did they update the anticheat?
> Chrysls has put in a workaround for it already a while ago. Probably the addresses need to be updated for it.
> And noclip might not be really feasable in a server as once the player is outside the bounds of the map they are automatically killed, and that's serverside. I think you could spoof your camera coordinates to get a freecam.

I mean in old version.
It's really can be.

**Comment by t1f7** [comment]
> I mean in old version.
> It's really can be.
> Tell me how to noclip and bypass the anticheat.

If they enable server-side anticheat (some servers disable it for optimisation) you hardly can use noclip. If you want to noclip here and there so really much you should find another server.

**Comment by totorowldox** [comment]
Hey bro.
I think I can do aimbot.
but how?
Now my progress:CharacterClassManager + 0x70 ==> camera
But idk what offset should i override the Transform->rotation

**Comment by t1f7** [comment]
> Hey bro.
> I think I can do aimbot.
> but how?
> Now my progress:CharacterClassManager + 0x70 ==> camera
> But idk what offset should i override the Transform->rotation

They don't use Euler angles but some shit instead (Quaternion angles) so I can't help with it. I'm really bored trying to make "angles aimbot" with it.

**Comment by totorowldox** [comment]
> > Hey bro.
> > I think I can do aimbot.
> > but how?
> > Now my progress:CharacterClassManager + 0x70 ==> camera
> > But idk what offset should i override the Transform->rotation
> 
> They don't use Euler angles but some shit instead (Quaternion angles) so I can't help with it. I'm really bored trying to make "angles aimbot" with it.

So how did you do that?

**Comment by t1f7** [comment]
> > > Hey bro.
> > > I think I can do aimbot.
> > > but how?
> > > Now my progress:CharacterClassManager + 0x70 ==> camera
> > > But idk what offset should i override the Transform->rotation
> > 
> > 
> > They don't use Euler angles but some shit instead (Quaternion angles) so I can't help with it. I'm really bored trying to make "angles aimbot" with it.
> 
> So how did you do that?

mouse events

**Comment by totorowldox** [comment]
> > > > Hey bro.
> > > > I think I can do aimbot.
> > > > but how?
> > > > Now my progress:CharacterClassManager + 0x70 ==> camera
> > > > But idk what offset should i override the Transform->rotation
> > > 
> > > 
> > > They don't use Euler angles but some shit instead (Quaternion angles) so I can't help with it. I'm really bored trying to make "angles aimbot" with it.
> > 
> > 
> > So how did you do that?
> 
> mouse events

I use SendInput but nothing happend in game.
wat function did you use?

**Comment by Matthew-AFK-Coder** [comment]
> I use SendInput but nothing happend in game.
> wat function did you use?

You can try this https://www.unknowncheats.me/forum/counterstrike-global-offensive/122534-cs-go-internal-external-aimbot-ready-c-p.html

**Comment by t1f7** [comment]
> > > > > Hey bro.
> > > > > I think I can do aimbot.
> > > > > but how?
> > > > > Now my progress:CharacterClassManager + 0x70 ==> camera
> > > > > But idk what offset should i override the Transform->rotation
> > > > 
> > > > 
> > > > They don't use Euler angles but some shit instead (Quaternion angles) so I can't help with it. I'm really bored trying to make "angles aimbot" with it.
> > > 
> > > 
> > > So how did you do that?
> > 
> > 
> > mouse events
> 
> I use SendInput but nothing happend in game.
> wat function did you use?

Current issue is "how to dump assembly". You should open new issue for "how to make aimbot" question, please.
