### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by JosiahBeaulieu** [chrysls/scp-internal-il2cpp#11]
Is it possible to use async with an injected DLL?
I've made a function that spits out some text on screen and after a while removes it, but when plugging it into std::async and running the function, I get a memory writing error.
I presume this is because I'm injecting into an advanced application like a game and it cannot tack on an address or whatever onto something. Not really sure why its happening.
If you have any hints or suggestions that would be much appreciated.
Here's my code:
```C++
	std::async([]() {
		if (GetAsyncKeyState(VK_INSERT)) {
			bool boolTime = true;
			if (boolTime) il2cpp::draw_text(Rect{ 1280, 100, 100.0f, 100.0f }, "<color=yellow><size=30>Sleeping for 3 seconds...</color></size>");
			Sleep(3000);
			boolTime = false;
		}
		}
	);
```

Here's a screenshot of the error:
![Screenshot_1](https://user-images.githubusercontent.com/26496268/84544386-7356e780-acfd-11ea-9bda-ee899305b7ef.png)

**Comment by JosiahBeaulieu** [comment]
From further research, I think I need a pointer? But idk what to do with that information.

**Comment by t1f7** [comment]
I guess you should update the offsets, probably. And try to get rid of Sleep, that's a bad idea.

**Comment by JosiahBeaulieu** [comment]
I don't know how to find those offsets, and yeah that sleep is bad but I don't know another way, that's why I'm using async as having that sleep froze everything, I'm looking into using system time to check when to remove the text. I'm trying to make a GUI in game for really no purpose but just to learn but now that I think of it, there's probably some address and offset that could be used to hook into Unity's GUI scripting thing.

**Comment by t1f7** [comment]
> I don't know how to find those offsets, and yeah that sleep is bad but I don't know another way, that's why I'm using async as having that sleep froze everything, I'm looking into using system time to check when to remove the text. I'm trying to make a GUI in game for really no purpose but just to learn but now that I think of it, there's probably some address and offset that could be used to hook into Unity's GUI scripting thing.

You're hooking GUI draw callback that is called each frame, you literally can't pause it.
You should find another way to make it.
For example, use `chorono` and variable (if (start - now).seconds < 3) { draw_text }

**Comment by JosiahBeaulieu** [comment]
That's a good idea! Looks like a better option than "GetTickCount()" of which I was using. Ill test it out but I need to get those new pointer values as the game just updated.

I've been working on getting them and I've been scanning the class number changes (the indexes from the table with all those class names) in CE and I've got a 26 addresses that Iv'e been using "Find out what accesses/writes to this address" on and getting what CE says might be the pointer but when searching for those addresses in CE again, I don't have any green addresses popping up they're all just black.
Not sure what I'm doing wrong but I'm going to keep researching and fumbling. But if you have any tips or suggestions that would be phenomenal! 
Anyways, thanks for the help so far!
