### ISSUE TITLE
Think I found offsets?

### ISSUE THREAD

**Issue by JosiahBeaulieu** [chrysls/scp-internal-il2cpp#12]
So I ran IDA on the packed GameAssembly.dll and found:
il2cpp_string_new = 0x10C8F0
il2cpp_resolve_icall = 0x10C1A0
Then again, it was packed so these are probably not correct, not sure, It didn't work when I tried compiling Plague with them, perhaps I need some others addresses/offsets as well?

I have as well dumped SCPSL using windows Task Manager and got a nice big 5GB .dmp file which I tried to throw into IDA which worked, but took four hours to get imported and another eight to  get at least 25% of all the addresses itemized or whatever, then it crashed.
Pretty sure the reason it took so long is that the dump contains a bunch of windows DLL's and other garbage I don't need and I should have used an address range to single out the GameAssembly.dll address's but I don't know how to find that range.

Anyways, I'm kind of stuck and hit the walls with Cheat Engine and IDA with this.
Alright, maybe those addresses help, idk.

**Comment by t1f7** [comment]
They are exported.
You can handle them without IDA like this:

```
auto gameAssembly = GetModuleHandleA("GameAssembly.dll");
auto il2cpp_string_new = GetProcAddress(gameAssembly, "il2cpp_string_new");
auto il2cpp_resolve_icall = GetProcAddress(gameAssembly, "il2cpp_resolve_icall");
```
Use AOB scanning for other stuff.

**Comment by JosiahBeaulieu** [comment]
I'll look into AOB's, so far they seem simple enough. But won't be posting for around a week as I have exams and, oh boy, I haven't studied!

**Comment by totorowldox** [comment]
> I'll look into AOB's, so far they seem simple enough. But won't be posting for around a week as I have exams and, oh boy, I haven't studied!

hello
Do you use CE for AOB scan?
I can found some varibles but how to scan function?(Im really lazy to look into manual :P)

**Comment by totorowldox** [comment]
> I'll look into AOB's, so far they seem simple enough. But won't be posting for around a week as I have exams and, oh boy, I haven't studied!

like "create text" function i searched "UnityEngine.GUI::Label(UnityEngine.Rect, UnityEngine.GUIContent, UnityEngine.GUIStyle)"
But nothing appeared
