### ISSUE TITLE
Как заставить работать это с другой игрой?

### ISSUE THREAD

**Issue by 1987kostya** [chrysls/scp-internal-il2cpp#14]
Какую часть кода нужно заменить, чтобы dll работал с другой игрой?

**Comment by 1987kostya** [comment]
Edit1:Мои самостоятельные эксперименты не увенчались успехом, так что я еще меньше стал понимать происходящее

**Comment by t1f7** [comment]
> Какую часть кода нужно заменить, чтобы dll работал с другой игрой?

Другая игра должна быть на Unity3D с il2cpp бэкэндом. Потребуется обновить оффсеты под свою игру, а именно файлы offsets.h, il2cpp.cpp и найти onGUI у той игры.

Собирай проект в такой же разрядности что и игра (x86 если игра x84, и x64 если игра x64).

**Comment by 1987kostya** [comment]
Спасибо.А чем стоит пробовать искать оффсеты?Просто я знаком только с dnSpy, у меня есть Dummy Assembly-CSharp.Там есть оффсеты, но какие именно нужно обновить?
Спасибо за ответ

**Comment by t1f7** [comment]
Тебе нужно обновить `il2cpp_string_new`, `il2cpp_resolve_icall` и GUI из offsets.h
Сделать это очень просто: https://github.com/chrysls/scp-internal-il2cpp/issues/12#issuecomment-643791593


А так же unity_create_text, unity_draw_text, unity_none_style в `il2cpp.cpp`

В `il2cpp.h` обновить под свою игру:
constexpr const char* assemblyName = "GameAssembly.dll";
constexpr const char* moduleName = "SCPSL.exe";

> чем стоит искать оффсеты

Да любой дампер il2cpp, вбей в поиск на github `il2cpp` там сразу они и будут со всеми инструкциями

**Comment by 1987kostya** [comment]
Спасибо.Если возникнут проблемы - обращусь за помощью,но просто так постараюсь не беспокоить

**Comment by 1987kostya** [comment]
Извини, что так много пишу, я немного туповат.Можешь поподробнее объяснить насчет вот этой

> А так же unity_create_text, unity_draw_text, unity_none_style в il2cpp.cpp
И вот этой <

> Да любой дампер il2cpp, вбей в поиск на github il2cpp там сразу они и будут со всеми инструкциями <
части.Просто я не совсем понял, что такое оффсеты и как их использовать

**Comment by t1f7** [comment]
> части.Просто я не совсем понял, что такое оффсеты и как их использовать

То есть, у тебя отсутствуют базовые сведения о работе с памятью на любом языке программирования. Затрудняюсь помочь в этом случае, учить тебя (или кого-либо ещё) базовым навыкам я точно не собираюсь :)
Рекомендую посмотреть ютуб или почитать статьи или даже книжку по этим темам.

**Comment by 1987kostya** [comment]
А можешь , пожалуйста,порекомендовать книгу или человека на ютубе?

**Comment by t1f7** [comment]
> А можешь , пожалуйста,порекомендовать книгу или человека на ютубе?

Ну разве что guidedhacking канал.. Хз вообще, книжки тоже лучше самому искать, смотря что тебе больше надо и к чему стремишься.




> Спасибо.А чем стоит пробовать искать оффсеты?Просто я знаком только с dnSpy, у меня есть Dummy Assembly-CSharp.Там есть оффсеты, но какие именно нужно обновить?
> Спасибо за ответ

В последней версии Cheat Engine нажми `dissect mono`, они добавили поддержку il2cpp. Поиск по классам тоже работает. Ну, например, `FirstPersonController` или `Pickup`.
