### ISSUE TITLE
I want to make it work with secret neighbor

### ISSUE THREAD

**Issue by noobhax1543** [chrysls/scp-internal-il2cpp#15]
Hi. I have a question for you. I want to make cheats for the "Secret Neighbor". I made a table for the Cheat Engine and it works good, but I would like to move its functionality to the DLL and add some new cheats(like ESP or something). I know that I have to replace the offsets in offsets.h and il2cpp.cpp files(I learned this from correspondence with the Russian programmer). I am familiar with working in  IDA, but finding offsets is new to me. I would appreciate it if you gave me a tip for finding offsets.
Thanks

**Comment by t1f7** [comment]
use il2cpp dumper, for example this one: https://github.com/Perfare/Il2CppDumper

**Comment by t1f7** [comment]
> Hi. I have a question for you. I want to make cheats for the "Secret Neighbor". I made a table for the Cheat Engine and it works good, but I would like to move its functionality to the DLL and add some new cheats(like ESP or something). I know that I have to replace the offsets in offsets.h and il2cpp.cpp files(I learned this from correspondence with the Russian programmer). I am familiar with working in IDA, but finding offsets is new to me. I would appreciate it if you gave me a tip for finding offsets.
> Thanks

Lol, it's obfuscated in some places. It will take more time to understand what was obfuscated and what that parts are doing.

**Comment by t1f7** [comment]
![preview](https://media.discordapp.net/attachments/703907529159213090/724739849717809182/unknown.png)

almost done it, finding some issues with viewmatrix or camera position or both

**Comment by M0n7y5** [comment]
@chrysls Do u have Discord? I wanna use your base for another game, i need little help with one small thing and i dont wanna create new github issue for it ...

**Comment by chrysls** [comment]
> @chrysls Do u have Discord? I wanna use your base for another game, i need little help with one small thing and i dont wanna create new github issue for it ...

Тиф#1648
