### ISSUE TITLE
What hooking method does it use 

### ISSUE THREAD

**Issue by Ninetys99** [chrysls/scp-internal-il2cpp#18]

**Comment by t1f7** [comment]
it's veh hooking: https://github.com/chrysls/scp-internal-il2cpp/blob/master/veh.h

**Comment by Ninetys99** [comment]
is veh pageguard?

**Comment by t1f7** [comment]
> is veh pageguard?

Vectored Exception Handler catches exceptions. Pageguard also throws an exception. But the way I use is writing `int 3` byte to force breakpoint.
