### ISSUE TITLE
How can I make buttons to create a menu?

### ISSUE THREAD

**Issue by Matthew-AFK-Coder** [chrysls/scp-internal-il2cpp#19]
Show me an example please.
I have the offset of "gui.button" but I don't know how write the function and what "gui.content" and "gui.style" I need.
As you can see I have a bool function to create it:
https://user-images.githubusercontent.com/67508883/85930713-eeec9300-b8be-11ea-9f2f-e97ada7962e3.png

**Comment by t1f7** [comment]
I'm not sure if that will work this way. I will check when I have free time.

**Comment by t1f7** [comment]
> Matthew-AFK-Coder

are u Matthew_-#2104 ?

**Comment by Matthew-AFK-Coder** [comment]
Yes, you are in that discord right?

**Comment by t1f7** [comment]
> Yes, you are in that discord right?

Yeah, but I don't see you at the server anymore. You asked me `Your hack have a virus ...? Tell me how i delete ...`, but there never was a signle virus or kind of that :)

**Comment by Matthew-AFK-Coder** [comment]
okay :)

**Comment by Matthew-AFK-Coder** [comment]
And what did you say about the ip? I did not understand that

**Comment by t1f7** [comment]
> And what did you say about the ip? I did not understand that

add me at discord we'll talk about that personally :)
