### ISSUE TITLE
How can i fixed this problem?

### ISSUE THREAD

**Issue by totorowldox** [chrysls/scp-internal-il2cpp#2]
i inject this dll to the game and after sometime the game crashed.
**HOW can i fixed that?**

and one question
How can i get playerroles and itemtypes?

_(Forgive me for bad English ;P)_

**Comment by t1f7** [comment]
You should provide information about crash. What's the error?



> How can i get playerroles and itemtypes?

All game information for GameObject has a pointer to that game object. You can combine player role with "GameObject" from api, but you have to find a way to get that data. This project doesn't cover the case.

**Comment by totorowldox** [comment]
> You should provide information about crash. What's the error?
OK.The game crashed about 5 minutes after I entered the server.
I guess it may be because someone quit the game when the cheat refreshes the screen.Is that right?

**Comment by totorowldox** [comment]
> You should provide information about crash. What's the error?

OK.The game crashed about 5 minutes after I entered the server.
I guess it may be because someone quit the game when the cheat refreshes the screen.Is that right?

**Comment by t1f7** [comment]
> OK.The game crashed about 5 minutes after I entered the server.
> I guess it may be because someone quit the game when the cheat refreshes the screen.Is that right?
Doesn't it show the message box with error? I can't help you without logs, errors or crash dump.

**Comment by totorowldox** [comment]
That's ok.
error.log: https://paste.ubuntu.com/p/YS3STjZKTq/
Player.log: https://paste.ubuntu.com/p/tjDGKNXSMw/

**Comment by t1f7** [comment]
Invalid address access problem.
Try to move `il2cpp::Init();` into the loop (after `gui::text("il2cpp plague : v0.1", 15, 15, 255, 0, 0);`) to check if error disappears.

Probably address of something changes in runtime, I'm not sure what is that.

**Comment by totorowldox** [comment]
That worked!
THX bro.
If I still have questions, I will ask in this issue.
