### ISSUE TITLE
How to AOB scan?

### ISSUE THREAD

**Issue by totorowldox** [chrysls/scp-internal-il2cpp#22]
Can CE do this?
I can use CE to found some varibles but how to scan function?
IOW how can i get array to scan?

**Comment by totorowldox** [comment]
Oh i know.
Dissect mono in CE.

**Comment by t1f7** [comment]
https://github.com/chrysls/scp-internal-il2cpp/issues/14#issuecomment-650975669

This is not AOB scanning btw

**Comment by totorowldox** [comment]
> [#14 (comment)](https://github.com/chrysls/scp-internal-il2cpp/issues/14#issuecomment-650975669)
> 
> This is not AOB scanning btw

oh i know.
I use these address to update offset but nothing happend.

**Comment by totorowldox** [comment]
> [#14 (comment)](https://github.com/chrysls/scp-internal-il2cpp/issues/14#issuecomment-650975669)
> 
> This is not AOB scanning btw

Im sure I update all the address that may change.

**Comment by t1f7** [comment]
> I use these address to update offset but nothing happend.

Right click on method -> click first option. That will lead you to the function memory address.

**Comment by totorowldox** [comment]
> > I use these address to update offset but nothing happend.
> 
> Right click on method -> click first option. That will lead you to the function memory address.

I just use this.

**Comment by totorowldox** [comment]
> Right click on method -> click first option. That will lead you to the function memory address.

Do i need to give you the address?

**Comment by totorowldox** [comment]
> > I use these address to update offset but nothing happend.
> 
> Right click on method -> click first option. That will lead you to the function memory address.

Look into my [fork](https://github.com/totorowldox/scp-internal-il2cpp)

**Comment by totorowldox** [comment]
> > I use these address to update offset but nothing happend.
> 
> Right click on method -> click first option. That will lead you to the function memory address.

Did I get the offset wrong?

**Comment by t1f7** [comment]
> > > I use these address to update offset but nothing happend.
> > 
> > 
> > Right click on method -> click first option. That will lead you to the function memory address.
> 
> Did I get the offset wrong?

There's no AC bypass, you should fix PAGE_GUARD veh hooking or find another way to bypass ac.

**Comment by totorowldox** [comment]
> > > > I use these address to update offset but nothing happend.
> > > 
> > > 
> > > Right click on method -> click first option. That will lead you to the function memory address.
> > 
> > 
> > Did I get the offset wrong?
> 
> There's no AC bypass, you should fix PAGE_GUARD veh hooking or find another way to bypass ac.

Does old sigs are still working?

Edit1: Sigs seem to be changed.
![fucking table](https://imgur.com/1TEByJ4.png)

**Comment by totorowldox** [comment]
I'm too weak to understand the form.

**Comment by t1f7** [comment]
> I'm too weak to understand the form.

https://www.unknowncheats.me/forum/general-programming-and-reversing/154643-different-ways-hooking.html

**Comment by totorowldox** [comment]
Im looking into it.
Waiting for your update :P

**Comment by t1f7** [comment]
they removed memory integrity checks, check wiki to update offsets, closed.

https://github.com/chrysls/scp-internal-il2cpp/wiki
