### ISSUE TITLE
Can't get it to Inject/Work

### ISSUE THREAD

**Issue by Fruitistic** [chrysls/scp-internal-il2cpp#24]
I have managed to compile the source code into a .dll, however when I try to inject it into the game nothing happens. I am using GH Injector, is it the injector's problem or is the code not compatible with the current game version? If so, how do I update it? Thanks alot!! :D

**Comment by totorowldox** [comment]
Oh boy.
Update the offset and fix the hook to bypass ac.
But idk how to fix the page guard. ;P

**Comment by totorowldox** [comment]
> Oh boy.
> Update the offset and fix the hook to bypass ac.
> But idk how to fix the page guard. ;P

Im also waiting chrysls to update

**Comment by totorowldox** [comment]
offset can be found in [my fork](https://github.com/totorowldox/scp-internal-il2cpp/).

**Comment by t1f7** [comment]
> I have managed to compile the source code into a .dll, however when I try to inject it into the game nothing happens. I am using GH Injector, is it the injector's problem or is the code not compatible with the current game version? If so, how do I update it? Thanks alot!! :D

Guys you have to do bypass on your own, every bypass I release they (game devs) will fix. They have already fixed previous one (it could be updated to fix over their fix but wtf how far would we go in it)

**Comment by Fruitistic** [comment]
How do you make your bypass? With Visual Studio? Please teach me how xd thank you

**Comment by totorowldox** [comment]
The cheat has the same problem with the oldest version. It will crash the game.

**Comment by t1f7** [comment]
> The cheat has the same problem with the oldest version. It will crash the game.

Did you update the offsets ? (https://github.com/chrysls/scp-internal-il2cpp/wiki)

**Comment by totorowldox** [comment]
> > The cheat has the same problem with the oldest version. It will crash the game.
> 
> Did you update the offsets ? (https://github.com/chrysls/scp-internal-il2cpp/wiki)

It works on the game but will crash the game after some time sometimes.

**Comment by t1f7** [comment]
> It works on the game but will crash the game after some time sometimes.

Well, you have VectoredExceptionHandler, so, you could change it to handle all exceptions haha

**Comment by altoms** [comment]
> > I have managed to compile the source code into a .dll, however when I try to inject it into the game nothing happens. I am using GH Injector, is it the injector's problem or is the code not compatible with the current game version? If so, how do I update it? Thanks alot!! :D
> 
> Guys you have to do bypass on your own, every bypass I release they (game devs) will fix. They have already fixed previous one (it could be updated to fix over their fix but wtf how far would we go in it)

how to do the bypass?
can you make the tutorial pls?

**Comment by t1f7** [comment]
> > > I have managed to compile the source code into a .dll, however when I try to inject it into the game nothing happens. I am using GH Injector, is it the injector's problem or is the code not compatible with the current game version? If so, how do I update it? Thanks alot!! :D
> > 
> > 
> > Guys you have to do bypass on your own, every bypass I release they (game devs) will fix. They have already fixed previous one (it could be updated to fix over their fix but wtf how far would we go in it)
> 
> how to do the bypass?
> can you make the tutorial pls?

AFAIK they disabled memory integrity checks so this repo works as is.
