### ISSUE TITLE
Offset AOB outdated?

### ISSUE THREAD

**Issue by ApEye** [chrysls/scp-internal-il2cpp#27]
When searching in Cheat Engine for any of the AOB's provided in the wiki you added in an attempt toupdate the offsets, I come up with no results.

**Comment by t1f7** [comment]
> When searching in Cheat Engine for any of the AOB's provided in the wiki you added in an attempt toupdate the offsets, I come up with no results.

Make sure you untick [x] Writable, because AOB would search unwritable-executable functions in .text

**Comment by ApEye** [comment]
That was the issue, I got them now thank you. I still crash on injection but that's a different issue so I'll close this one.
Thanks again!

**Comment by t1f7** [comment]
> That was the issue, I got them now thank you. I still crash on injection but that's a different issue so I'll close this one.
> Thanks again!

Make sure you get the start of the function, some AOBs (draw_text, no_style) could scan middle of function and you should find its start.

**Comment by Saterlite** [comment]
> That was the issue, I got them now thank you. I still crash on injection but that's a different issue so I'll close this one.
> Thanks again!
Are you getting an error which an instruction is trying to access an address that has nothing in it?

**Comment by ApEye** [comment]
> Make sure you get the start of the function, some AOBs (draw_text, no_style) could scan middle of function and you should find its start.

You were right about that, I went back and fixed what I believe all the offsets to be at the top, and it's made a bit of progress, I get GUI text to print on the left side of the screen but it still crashes upon loading in, I'll attach a picture

> > Are you getting an error which an instruction is trying to access an address that has nothing in it?

I'm getting a memory error but not that one specifically, I'll attach a picture
![SCPSL_nrlNCCZPro](https://user-images.githubusercontent.com/46307237/91502574-61b1c480-e896-11ea-9890-3e1d75328322.png)

![scp2](https://user-images.githubusercontent.com/46307237/91509231-a5f99080-e8a7-11ea-9e19-ac20220dab33.png)

**Comment by t1f7** [comment]
Obviously the problem in second hook (PlayerStats_Update), its called only when loaded on server.

ccm_team offset is 0x178 now.

**Comment by JosiahBeaulieu** [comment]
Ah yes, Obviously. I see now.
Thank you for your help.

**Comment by ApEye** [comment]
You're right, I was was a few bytes too high. Everythings working smoothly now, I appreciate the help!
