### ISSUE TITLE
Player info.

### ISSUE THREAD

**Issue by oeant** [chrysls/scp-internal-il2cpp#3]
Hello, how can i get player name, class (mtf, chaos, etc..), and also i tried to do 914 esp, i tried to find object „914_use” but it looks like showed possision is wrong.

**Comment by t1f7** [comment]
v0.2 uploaded with example for "location esp"

I don't know how to get player class without hooks. Use any hook at player::update method for example.

**Comment by oeant** [comment]
Are you planning to release example of il2cpp method hooking in this base?

**Comment by t1f7** [comment]
> Are you planning to release example of il2cpp method hooking in this base?

It's not il2cpp hooking, it's basically hooking. For example, midfunction hooks or vmt hooks.
I don't know if I will release one, devs (scpsl team) would probably fix it. You should find your way.

**Comment by oeant** [comment]
What about making "listen all" cheat? Do i need to hook functions to make it?

**Comment by t1f7** [comment]
> What about making "listen all" cheat? Do i need to hook functions to make it?

You can hook or you can find pointer to static Radio class to manually write memory.

**Comment by Tracersboy** [comment]
> Hello, how can i get player name, class (mtf, chaos, etc..), and also i tried to do 914 esp, i tried to find object „914_use” but it looks like showed possision is wrong.

	vec3 get_transform_room(uint64_t entity) {
		auto transform = ((t_unity_get_transform*)unity_get_transform)(entity);
		if (!transform) return vec3{};
		auto posdata = Read<uint64_t>((uint64_t)transform + offset::transform_room_1);
		if (!posdata) return vec3{};
		posdata = Read<uint64_t>((uint64_t)posdata + offset::transform_room_2);
		if (!posdata) return vec3{};
		posdata = Read<uint64_t>((uint64_t)posdata + offset::transform_room_3);
		return Read<vec3>(posdata + offset::transform_room_4);
	}

 //most GameObject whose tag is “room“ have offset for position like this except HID room ,ammo room and HCZ_EZ_Checkpoint room

	constexpr ::std::uint64_t transform_room_1 = 0x10;
	constexpr ::std::uint64_t transform_room_2 = 0x30;
	constexpr ::std::uint64_t transform_room_3 = 0x218;
	constexpr ::std::uint64_t transform_room_4 = 0xE0;

**Comment by oeant** [comment]
@Tracersboy do you know any way to find all available tags so i can use them in this cheat?

**Comment by Tracersboy** [comment]
> @Tracersboy您知道找到所有可用标签的任何方法，以便我可以在此作弊中使用它们吗？

hhhhh，I just finished it
https://github.com/chrysls/scp-internal-il2cpp/issues/1

**Comment by oeant** [comment]
Thank you very much!

**Comment by oeant** [comment]
After some testing (original version, i didnt made any changes to code) the game just crashes after few minutes of playing.

**Comment by Tracersboy** [comment]
> 经过一些测试（原始版本，我没有对代码进行任何更改），游戏在玩了几分钟后便崩溃了。

Uninstalling and installing might be a good idea

**Comment by oeant** [comment]
I assume that you are talking about reinstalling game, okay i will try that.

**Comment by Tracersboy** [comment]
> I assume that you are talking about reinstalling game, okay i will try that.

sry，I misunderstood your meaning, and I also encountered the same problem. I think this is caused by frequent acquisition of player coordinates. Maybe the coordinate offset address of the player who just entered the server is unreadable. For this reason, it reported an error, but it's just my guess. The error log may have prompts, but I don't know how to read it (I only use it for room ESP, read it once a round)

**Comment by oeant** [comment]
It seems that nothing has changed, still crashing.

**Comment by Tracersboy** [comment]
> It seems that nothing has changed, still crashing.

https://github.com/chrysls/scp-internal-il2cpp/issues/2  
same question

**Comment by oeant** [comment]
SCPSL.gc.log:
Collecting from unknown thread

**Comment by Tracersboy** [comment]
> SCPSL.gc.log:
> Collecting from unknown thread

The author said：

Invalid address access problem.
Try to move il2cpp::Init(); into the loop (after gui::text("il2cpp plague : v0.1", 15, 15, 255, 0, 0);) to check if error disappears.

Probably address of something changes in runtime, I'm not sure what is that.

**Comment by oeant** [comment]
This is already fixed in v0.2, which im trying to use, error is still existing

**Comment by Tracersboy** [comment]
> v0.2已修复该问题，我正在尝试使用，错误仍然存​​在

If vs is installed, you can use VS to open DMP file for debugging. You can copy the stack information at the time of crash to see where the crash started. If it is caused by its own DLL, loading its own PDB symbol file can locate the place where its code crashes

C:\Users\your username\AppData\Local\Temp\Hubert Moszka\SCPSL\Crashes\

**Comment by oeant** [comment]
Yeah, i opened it, i have also "error.log" and "Player.log"

**Comment by oeant** [comment]
One of the errors: "ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF889B1D4FA)"

**Comment by t1f7** [comment]
> SCPSL.gc.log:
> Collecting from unknown thread

I will add fix to this in v0.3, that's il2cpp garbage collector (GC) issue.

**Comment by oeant** [comment]
Okay, when can we expect it to be out?

**Comment by t1f7** [comment]
> Okay, when can we expect it to be out?

Right now.

**Comment by oeant** [comment]
Thank you, seems to work. I found a bool "roundEnded" in radio class, can i somehow offset it and change to true??

**Comment by t1f7** [comment]
> Thank you, seems to work. I found a bool "roundEnded" in radio class, can i somehow offset it and change to true??

Why not? bool is [1 byte], 1 or 0.

**Comment by oeant** [comment]
How can i get the offset? I know that the field offset in Radio class is 0x9

**Comment by totorowldox** [comment]
> How can i get the offset? I know that the field offset in Radio class is 0x9

![roundEnded](https://t1.picb.cc/uploads/2020/05/22/koZwgR.png)
Here is 0x9,right?

then open **script.json** and find the **Class$Radio**
![Class$Radio](https://t1.picb.cc/uploads/2020/05/22/koZcOK.png)
So you can know the radio class offset.

**Comment by totorowldox** [comment]
One more thing
the roundended is STATIC
Soooo the radioclass must add 0xB8 then add 0x9

**Comment by oeant** [comment]
so 0x30785144 + 0xB8 + 0x9?

**Comment by totorowldox** [comment]
> so 0x30785144 + 0xB8 + 0x9?

30785144 not HEX
that is DEC

so 0x1D5BE78

**Comment by oeant** [comment]
And now with some WriteMemory function i can change value of this bool to 1?

**Comment by totorowldox** [comment]
You'd better make a judgment
(Don't care about C#)
```
                long Radio = Memory.ReadMemory<long>((long)Memory.GameAssemblyModule.BaseAddress + Offset.RadioOffset);
                if (Radio != 0)
                {
                    long RadioClass = Memory.ReadMemory<long>(Radio + 0xB8);   //static
                    if (RadioClass != 0)
                    {
                        Memory.WriteMemory<bool>(RadioClass + 0x9, Settings.AllRadio);
                    }
                }
```


> And now with some WriteMemory function i can change value of this bool to 1?

YEP

**Comment by oeant** [comment]
cool, thank you for help

**Comment by Tracersboy** [comment]
> > How can i get the offset? I know that the field offset in Radio class is 0x9
> 
> ![roundEnded](https://camo.githubusercontent.com/b3c27092c1335189d2876753ea2ce955020a5fcb/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a7767522e706e67)
> Here is 0x9,right?
> 
> then open **script.json** and find the **Class$Radio**
> ![Class$Radio](https://camo.githubusercontent.com/64b27709c388a327b76b0a8129db064d42814072/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a634f4b2e706e67)
> So you can know the radio class offset.

I really want to know where “ script.json”  is，cloud you tell me how to get it :)

**Comment by totorowldox** [comment]
> > > How can i get the offset? I know that the field offset in Radio class is 0x9
> > 
> > 
> > ![roundEnded](https://camo.githubusercontent.com/b3c27092c1335189d2876753ea2ce955020a5fcb/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a7767522e706e67)
> > Here is 0x9,right?
> > then open **script.json** and find the **Class$Radio**
> > ![Class$Radio](https://camo.githubusercontent.com/64b27709c388a327b76b0a8129db064d42814072/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a634f4b2e706e67)
> > So you can know the radio class offset.
> 
> I really want to know where “ script.json” is，cloud you tell me how to get it :)

[il2cppdumper](https://github.com/Perfare/Il2CppDumper)

**Comment by oeant** [comment]
![Screenshot_71](https://user-images.githubusercontent.com/65570466/82663112-5b74d200-9c2f-11ea-88ed-2b8cfedf9ccc.png)
Will this function work?

**Comment by totorowldox** [comment]
> ![Screenshot_71](https://user-images.githubusercontent.com/65570466/82663112-5b74d200-9c2f-11ea-88ed-2b8cfedf9ccc.png)
> Will this function work?

IDK about that
but you can try

**Comment by Tracersboy** [comment]
> > > > How can i get the offset? I know that the field offset in Radio class is 0x9
> > > 
> > > 
> > > ![roundEnded](https://camo.githubusercontent.com/b3c27092c1335189d2876753ea2ce955020a5fcb/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a7767522e706e67)
> > > Here is 0x9,right?
> > > then open **script.json** and find the **Class$Radio**
> > > ![Class$Radio](https://camo.githubusercontent.com/64b27709c388a327b76b0a8129db064d42814072/68747470733a2f2f74312e706963622e63632f75706c6f6164732f323032302f30352f32322f6b6f5a634f4b2e706e67)
> > > So you can know the radio class offset.
> > 
> > 
> > I really want to know where “ script.json” is，cloud you tell me how to get it :)
> 
> [il2cppdumper](https://github.com/Perfare/Il2CppDumper)

I've seen this project before, but I never found global- metadata.dat，forgive my stupidity

**Comment by totorowldox** [comment]
> I've seen this project before, but I never found global- metadata.dat，forgive my stupidity

SCP Secret Laboratory\SCPSL_Data\il2cpp_data\Metadata\global-metadata.dat

**Comment by Tracersboy** [comment]
> > I've seen this project before, but I never found global- metadata.dat，forgive my stupidity
> 
> SCP Secret Laboratory\SCPSL_Data\il2cpp_data\Metadata\global-metadata.dat

thank you bro，You helped me a lot. I used to think that all data file in this game like assembly- CSharp.dll was exist in the dedicated server, but I am wrong

**Comment by Tracersboy** [comment]
> > I've seen this project before, but I never found global- metadata.dat，forgive my stupidity
> 
> SCP Secret Laboratory\SCPSL_Data\il2cpp_data\Metadata\global-metadata.dat

 Can't use auto mode to process file, try manual mode.
CodeRegistration=
MetadataRegistration=
what is it?

**Comment by totorowldox** [comment]
> > > I've seen this project before, but I never found global- metadata.dat，forgive my stupidity
> > 
> > 
> > SCP Secret Laboratory\SCPSL_Data\il2cpp_data\Metadata\global-metadata.dat
> 
> Can't use auto mode to process file, try manual mode.
> CodeRegistration=
> MetadataRegistration=
> what is it?


executable-file must be GameAssembly.dll

**Comment by Tracersboy** [comment]
> GameAssembly.dll

You are full of wisdom，I love you bro

**Comment by totorowldox** [comment]
> > GameAssembly.dll
> 
> You are full of wisdom，I love you bro

you are so politely

**Comment by totorowldox** [comment]
> ![Screenshot_71](https://user-images.githubusercontent.com/65570466/82663112-5b74d200-9c2f-11ea-88ed-2b8cfedf9ccc.png)
> Will this function work?

Is that worked?
Have you tried?

**Comment by Tracersboy** [comment]
> One more thing
> the roundended is STATIC
> Soooo the radioclass must add 0xB8 then add 0x9

I can't understand “0xB8”，I didn't find it

**Comment by oeant** [comment]
I tried and it didnt worked, i think that this is my function issue

**Comment by totorowldox** [comment]
> > One more thing
> > the roundended is STATIC
> > Soooo the radioclass must add 0xB8 then add 0x9
> 
> I can't understand “0xB8”，I didn't find it

Can i say idk that too?
I also listen to others.
I heard one way is to use CE

**Comment by totorowldox** [comment]
> I tried and it didnt worked, i think that this is my function issue

i guess you can use WriteProcessMemory

**Comment by Tracersboy** [comment]
> > > One more thing
> > > the roundended is STATIC
> > > Soooo the radioclass must add 0xB8 then add 0x9
> > 
> > 
> > I can't understand “0xB8”，I didn't find it
> 
> Can i say idk that too?
> I also listen to others.
> I heard one way is to use CE

okey，i just remember it

**Comment by oeant** [comment]
what is CE?

**Comment by totorowldox** [comment]
> what is CE?

CheatEngine

**Comment by Tracersboy** [comment]
> what is CE?
It is useful，i am tring
![image](https://user-images.githubusercontent.com/48148867/82667558-a829ce80-9c6a-11ea-8dff-b46586e25dc4.png)

**Comment by oeant** [comment]
Do you have any working writememory function?

**Comment by t1f7** [comment]
> > so 0x30785144 + 0xB8 + 0x9?
> 
> 30785144 not HEX
> that is DEC
> 
> so 0x1D5BE78

Thanks for contribution.

> ![Screenshot_71](https://user-images.githubusercontent.com/65570466/82663112-5b74d200-9c2f-11ea-88ed-2b8cfedf9ccc.png)
> Will this function work?

You don't need a function to write memory, check how function is hooked in v0.4

Kind of this (not tested) one-line solution could work: 
```cpp
bool isOn = true;
*(bool*)(*(uint64_t*)(*(uint64_t*)(GetBase() + 0x1D5BE78) + 0xB8) + 0x9) = isOn;
```

**Comment by totorowldox** [comment]
hey guys.
i think that here is "int64_t" not "uint64_t" cuz in C# long is 8 byte
```C++
int64_t Radio = Read<int64_t>((int64_t)il2cpp::GetModuleBase() + 0x1D5BE78);
		if (Radio != 0)
		{
			int64_t RadioClass = Read<int64_t>(Radio + 0xB8);
			if (RadioClass != 0)
			{
				*(bool*)(*(int64_t*)RadioClass + 0x9) = true;
			}
		}
```

**Comment by totorowldox** [comment]
> hey guys.
> i think that here is "int64_t" not "uint64_t" cuz in C# long is 8 byte
> 
> ```c++
> int64_t Radio = Read<int64_t>((int64_t)il2cpp::GetModuleBase() + 0x1D5BE78);
> 		if (Radio != 0)
> 		{
> 			int64_t RadioClass = Read<int64_t>(Radio + 0xB8);
> 			if (RadioClass != 0)
> 			{
> 				*(bool*)(*(int64_t*)RadioClass + 0x9) = true;
> 			}
> 		}
> ```

I tried this but nothing occured.

**Comment by totorowldox** [comment]
> ```c++
> bool isOn = true;
> *(bool*)(*(uint64_t*)(*(uint64_t*)(GetBase() + 0x1D5BE78) + 0xB8) + 0x9) = isOn;
> ```

I tried this but nothing occured.

**Comment by t1f7** [comment]
Ok, PlayerInfo data fetching exposed in v0.5+, open new thread pls if needed (too much messages here)
