### ISSUE TITLE
how is this meant to be injected?

### ISSUE THREAD

**Issue by iraizo** [chrysls/scp-internal-il2cpp#32]
ive tried to use manual map and loadliba and both seem to crash at 0xFFFFFFFF

**Comment by t1f7** [comment]
Did you compile it as x64 ?

**Comment by iraizo** [comment]
i did

**Comment by t1f7** [comment]
> i did

Release build ?

**Comment by iraizo** [comment]
Yes i know

**Comment by iraizo** [comment]
guess im not getting an answer to this
