### ISSUE TITLE
Player locations are restricted by server now

### ISSUE THREAD

**Issue by JosiahBeaulieu** [chrysls/scp-internal-il2cpp#33]
Sadly, a new update has introduced a feature which limits what player locations are sent to the client. Any player over 42 meters away from the user (you) cannot be seen, the server sends null location data for those players to the user (you).
Only in spectator does the server send all player's location data.
You can however still see the location of players on different levels (LCZ, HCZ, Entrance) but as soon as you are on that same level, player location data for players is restricted.

Player classes are still however available globally.
I don't think there is a work around, I tried fooling my client to believe it was a spectator but that only glitched the camera and did not fool the server into sending all player's location data.
It's possible to run two clients, on spectator and one that you play on, on the server, and network them, but that's more that it's worth I think.

Anyways, the client is still useful but not as it has been before, unless you backdoor the server, now that would be epic. And possibly easy? NorthWood and Unity are not the most safest in security standards, and there might be some forgotten port or packet intercepts that can provide a peel to pull on.

**Comment by t1f7** [comment]
They had this already but it seems like it was an optional feature and it's a default one now.
You can pretend to be a spectator but that won't fool a server.

> Anyways, the client is still useful but not as it has been before, unless you backdoor the server, now that would be epic. And possibly easy?

That's boring. Why won't one spawn fake client and share information, much easier.

**Comment by JosiahBeaulieu** [comment]
> Why won't one spawn fake client and share information, much easier.

Do you mean create a headless client?
That might actually be easier, if there isn't any encryption between the server and client we could intercept the packages and experiment with the data. Might be able to just send a couple packages to server from a python script. And reconnect to cause the headless client to spawn as spectator always. Though, I don't know how steam's API will work, I don't think the API has any documentation over client side interactions like logging in.

Ill prod around with wireshark and see if I can find anything.

Edit: It uses Mirror open-source networking, there's quite a bit documentation on it so Ill look into that too.
