### ISSUE TITLE
How to find view angle offset?

### ISSUE THREAD

**Issue by yuimin4751** [chrysls/scp-internal-il2cpp#35]
I want make aimbot
so I did try find view angle offset in entity but i couldn't find view angle offset
how to find view angle offset?

**Comment by t1f7** [comment]
This game (game engine) doesn't use traditional `Euler` angles. It uses `Quartenion`s. Use Il2CppDumper to find structs and offsets.

**Comment by yuimin4751** [comment]
<img width="844" alt="dnspy" src="https://user-images.githubusercontent.com/72381554/95817987-c8fbd900-0d5d-11eb-92d9-04e5bce70401.PNG">
<img width="494" alt="cheat" src="https://user-images.githubusercontent.com/72381554/95818025-dfa23000-0d5d-11eb-9462-264788a8503e.PNG">

I looked for a struct with dnspy and found angle with CE, but
It doesn't seem to be this value. Isn't it a Quaternion struct?

**Comment by t1f7** [comment]
> Isn't it a Quaternion struct?

It is.
