### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by hexappp** [chrysls/scp-internal-il2cpp#37]
playerstats pattern scan aob code isn't working.How to get playerstats offset?

**Comment by totorowldox** [comment]
What are you doing?:P
This is a RLLY old repo.
Just use your il2cppdumper AND dnspy.

_However, it's not recommanded to write an internal chea cuz of there anticheat._

**Comment by totorowldox** [comment]
What are you doing?:P
This is a RLLY old repo.
Just use your il2cppdumper AND dnspy.

However, it's not recommended to write an internal cheat cuz of their anticheat.
