### ISSUE TITLE
Function hooking.

### ISSUE THREAD

**Issue by oeant** [chrysls/scp-internal-il2cpp#4]
i see in the new update how to hook function, but how about just calling game function and getting result? For example calling get_ItemId() and getting the result in our cheat?

**Comment by totorowldox** [comment]
one example “NoSearchTime” in c#

```CSharp
long Pickup = Memory.ReadMemory<long>((long)Memory.GameAssemblyModule.BaseAddress + Offset.PickupOffset);
                    if (Pickup != 0)
                    {
                        long PickupStaticFields = Memory.ReadMemory<long>(Pickup + 0xB8);  //静态
                        if (PickupStaticFields != 0)
                        {
                            long Instances = Memory.ReadMemory<long>(PickupStaticFields + 0x8);
                            if (Instances != 0)
                            {
                                long Buffer = Memory.ReadMemory<long>(Instances + 0x10);
                                if (Buffer != 0)
                                {
                                    int Count = Memory.ReadMemory<int>(Instances + 0x18);
                                    for (int i = 0; i < Count; i++)
                                    {
                                        long Entity = Memory.ReadMemory<long>(Buffer + 0x20 + (i * 8));
                                        if (Entity != 0)
                                        {
                                            Memory.WriteMemory<float>(Entity + 0x50, 0);
                                            // do the function here
                                        }
                                    }
                                }
                            }
                        }
                    }
```

**Comment by t1f7** [comment]
> i see in the new update how to hook function, but how about just calling game function and getting result? For example calling get_ItemId() and getting the result in our cheat?

Check source, it has "FindFunction" and example how to call found one. You have to declare function btw

**Comment by oeant** [comment]
`long Buffer = Memory.ReadMemory<long>(Instances + 0x10);`
@totorowldox why are you adding 0x10 to "instances"? it is a list of all pickups right?

**Comment by totorowldox** [comment]
> `long Buffer = Memory.ReadMemory<long>(Instances + 0x10);`
> @totorowldox why are you adding 0x10 to "instances"? it is a list of all pickups right?

yep,
instances is a List<Pickup>

**Comment by oeant** [comment]
list offset is 0x10?

**Comment by totorowldox** [comment]
> list offset is 0x10?

right

**Comment by oeant** [comment]
what about getting ID for each pickup? can i do that similiar way?

**Comment by totorowldox** [comment]
> what about getting ID for each pickup? can i do that similiar way?

I have not tried but you can try

**Comment by oeant** [comment]
@chrysls why did you added 0x50 to the function offset?

**Comment by t1f7** [comment]
> @chrysls why did you added 0x50 to the function offset?

Because it's not a function. It's class instance in heap (actually virtual table of methods) and I switched pointer to my own "method".

**Comment by t1f7** [comment]
well, version 0.5 and 0.6 already showed how to hook functions with different ways
