### ISSUE TITLE
no gui

### ISSUE THREAD

**Issue by rwdsfgds** [chrysls/scp-internal-il2cpp#5]
compiled it but there is no gui, it says in red top left it's injected however

**Comment by oeant** [comment]
there is no gui in this source, only the watermark in the top left.

**Comment by chrysls** [comment]
> compiled it but there is no gui, it says in red top left it's injected however

Yeah you should make one on your own, if you really need one. With open source code you can enable or disable what ever you wish, do you really need gui menu?

**Comment by oeant** [comment]
@chrysls about making gui, i tried to make my own imgui menu for this external overlay (ive done multiple internal implementations), menu is rendering normally but i cant interact with it. Do you know what can be reason for that?

**Comment by chrysls** [comment]
> @chrysls about making gui, i tried to make my own imgui menu for this external overlay (ive done multiple internal implementations), menu is rendering normally but i cant interact with it. Do you know what can be reason for that?

I guess this repo is not a good place for such questions. We discuss il2cpp and SCPSL here.
