### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by lachtan999** [chrysls/scp-internal-il2cpp#6]
Hello, I am trying to compile the source code of 0.4, but I always run into an problem. It says it is `d3dx9.h` in the `gui.h` file, in the `#include <d3dx9.h>` is missing (no such file or directory). I have both Direct X runtime and Direct X SDK from June 2010 installed? Any solution? I am using Visual Studio 2017.

**Comment by totorowldox** [comment]
> Hello, I am trying to compile the source code of 0.4, but I always run into an problem. It says it is `d3dx9.h` in the `gui.h` file, in the `#include <d3dx9.h>` is missing (no such file or directory). I have both Direct X runtime and Direct X SDK from June 2010 installed? Any solution? I am using Visual Studio 2017.

Add $(DXSDK_DIR)Include to VC++ Directory -> Include directory
and $(DXSDK_DIR)Lib\x64 to VC++ Directory -> Library directory

**Comment by lachtan999** [comment]
I already tested that, but it didnt work.

**Comment by totorowldox** [comment]
check your directory and make sure d3dxp.h exists

**Comment by totorowldox** [comment]
check your directory and make sure that "d3dx9.h" exists

**Comment by lachtan999** [comment]
Thanks, my install of DirectX SDK was damaged. I reinstalled it and now it works.
