### ISSUE TITLE
Problem about "il2cpp::draw_text"

### ISSUE THREAD

**Issue by totorowldox** [chrysls/scp-internal-il2cpp#7]
Can the function accept formats like _"<color=#BEBEBE>***</color>"_?

**Comment by totorowldox** [comment]
> Can the function accept formats like _"<color=#BEBEBE>***"_?

That's worked.
How can i change font?

**Comment by totorowldox** [comment]
and...
the text will tend right

**Comment by t1f7** [comment]
https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html
