### ISSUE TITLE
The text will be deviation to the right

### ISSUE THREAD

**Issue by totorowldox** [chrysls/scp-internal-il2cpp#8]
AFAIK the text will be deviation to the right.
And at different resolutions, the degree of deviation to the right is different.

**Comment by totorowldox** [comment]
800x600: ![800*600](https://i.imgur.com/Pnv8xEK.png)
1600x900: ![1600*900](https://imgur.com/JxtG3qe.png)

**Comment by t1f7** [comment]
main.cpp

```
const int Width = 1920;
const int Height = 1080;
```

change to used resolution. I'm too lazy to find actual resolution :)

**Comment by totorowldox** [comment]
> main.cpp
> 
> ```
> const int Width = 1920;
> const int Height = 1080;
> ```
> 
> change to used resolution. I'm too lazy to find actual resolution :)

I'll find the actual resolution
lmao

**Comment by totorowldox** [comment]
The Pickupclass has no method "Update"
Which method should i hook?
![lol](https://imgur.com/lDfLTFB.png)

**Comment by t1f7** [comment]
> The Pickupclass has no method "Update"
> Which method should i hook?
> ![lol](https://camo.githubusercontent.com/3e0006a83c245c3a151463bf3b5ee2ec83dd679a/68747470733a2f2f696d6775722e636f6d2f6c44664c5446422e706e67)

`LateUpdate`

**Comment by totorowldox** [comment]
hey bro.
the scopophobia has already been updated.

**Comment by totorowldox** [comment]
And....
![wtf?](https://imgur.com/vxtcPzn.png)
wtf?

**Comment by totorowldox** [comment]
I made a change when the cheat injected.
il2cpp.h:```typedef void t_AddLog(Il2CppString*, Color c, bool nospace);```

il2cpp.cpp:
```cpp
void Add_Log(const char* text, Color c) {
		auto il2cpp_string = ((il2cpp_string_new*)unity_string_new)(text);
		((t_AddLog*)AddLog)(il2cpp_string, c, false);
	}
```
main.cpp:
```cpp
DWORD WINAPI OnDllAttach(LPVOID inj_hModule)
{
	Sleep(2000);
	il2cpp::Add_Log("The Cheat has been injected.Enjoy your time! :P", Color{ 0.0f, 139.0f, 139.0f, 1.0f });
	return 1;
}
```
When i use `CreateThread(nullptr, 0, OnDllAttach, hinstDll, 0, nullptr);` in DllMain,the gameconsole print the message but crash quickly.

**Comment by t1f7** [comment]
> hey bro.
> the scopophobia has already been updated.

client-side AC.
bypass memory integrity checks or don't write to .data

**Comment by t1f7** [comment]
> And....
> ![wtf?](https://camo.githubusercontent.com/fac36d5ab9165a499c1da0067a126e46ab9bcc06/68747470733a2f2f696d6775722e636f6d2f76787463507a6e2e706e67)
> wtf?

packed GameAssembly.dll file

**Comment by totorowldox** [comment]
> > And....
> > ![wtf?](https://camo.githubusercontent.com/fac36d5ab9165a499c1da0067a126e46ab9bcc06/68747470733a2f2f696d6775722e636f6d2f76787463507a6e2e706e67)
> > wtf?
> 
> packed GameAssembly.dll file

so how can i fixed it?

**Comment by t1f7** [comment]
> > > And....
> > > ![wtf?](https://camo.githubusercontent.com/fac36d5ab9165a499c1da0067a126e46ab9bcc06/68747470733a2f2f696d6775722e636f6d2f76787463507a6e2e706e67)
> > > wtf?
> > 
> > 
> > packed GameAssembly.dll file
> 
> so how can i fixed it?

At-frist: Please, stop asking different questions that are offtopic. Nobody would find anything after, you should open new issue.

And then: I dunno, how to fix it.
